### ISSUE TITLE
Add offset + length params

### ISSUE THREAD

**Issue by ronag** [jungomi/xxhash-wasm#40]
So we can avoid creating unnecessary sub buffer intermediate, i.e.

```
h32(buf.subarray(2, 32))
```
vs

```
h32(buf, 2, 32)
```

**Comment by marcusdarmstrong** [comment]
The implementation would need to create the intermediate buffer if the user didn't (the subarray buffer being a view, so it's actually a pretty small, fixed size allocation), so there's not much to be saved here: 
https://github.com/jungomi/xxhash-wasm/blob/main/src/index.js#L142
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set

One could conceive of a different buffer write mechanism than `TypedArray.set` but alternatives quickly lose out to the speed of its underlying `memcpy` in practice, from my own microbenchmarking.

**Comment by ronag** [comment]
```
    h32Raw(inputBuffer, seed = defaultSeed, start = 0, length = null) {
      growMemory(length, 0);
      if (length == null) {
        memory.set(inputBuffer, start);
      } else {
        memory.set(new UInt8Array(inputBuffer, start, length));
      }
      return forceUnsigned32(xxh32(0, inputBuffer.byteLength, seed));
    },
```
