### ISSUE TITLE
Expose a streaming api?

### ISSUE THREAD

**Issue by thatmarvin** [jungomi/xxhash-wasm#9]
Any chance you'd consider exposing an api that'll enable hashing the content of a large file (that won't fit in memory)? Maybe the equivalent of the `XXH64_update` C api as used in [the streaming variant in this example here](https://github.com/Cyan4973/xxHash#example)?

Fantastic lib btw, it's a little shocking how fast this runs! 🚀

**Comment by jungomi** [comment]
That would certainly be interesting, but I have no plans to work on implementing new features, given that I don't really have time for it.

I'm open for pull requests to add such a feature, if anyone wanted to implement it.

**Comment by marcusdarmstrong** [comment]
I've implemented this for xxhash64 for my employer—Hopefully I'll be able to share it with you guys this spring, pending the legal hoops on our end to get it approved for open source publication internally.
